# fly.toml app configuration file generated for money-survey on 2026-06-24T15:55:15+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'money-survey'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3456
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256

[mounts]
  source = 'survey_data'
  destination = '/data'
